//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistony.PagosEfectuados.DAL.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English_United_States {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English_United_States() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vistony.PagosEfectuados.DAL.Idiomas.English_United_States", typeof(English_United_States).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ability.
        /// </summary>
        internal static string Aptitude {
            get {
                return ResourceManager.GetString("Aptitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispatch Date Assignment.
        /// </summary>
        internal static string Asignación_de_Fecha_de_despacho {
            get {
                return ResourceManager.GetString("Asignación_de_Fecha_de_despacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assistant.
        /// </summary>
        internal static string Ayudante {
            get {
                return ResourceManager.GetString("Ayudante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search by Date Range.
        /// </summary>
        internal static string Busqueda_por_Rango_Fecha {
            get {
                return ResourceManager.GetString("Busqueda_por_Rango_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ability.
        /// </summary>
        internal static string Capacidad {
            get {
                return ResourceManager.GetString("Capacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To close.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driver.
        /// </summary>
        internal static string Chofer {
            get {
                return ResourceManager.GetString("Chofer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SN code.
        /// </summary>
        internal static string Codigo_SN {
            get {
                return ResourceManager.GetString("Codigo_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With Agency.
        /// </summary>
        internal static string Con_Agencia {
            get {
                return ResourceManager.GetString("Con_Agencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidation of deliveries.
        /// </summary>
        internal static string Consolidación_de_entregas {
            get {
                return ResourceManager.GetString("Consolidación_de_entregas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidated.
        /// </summary>
        internal static string Consolidado {
            get {
                return ResourceManager.GetString("Consolidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidate.
        /// </summary>
        internal static string Consolidar {
            get {
                return ResourceManager.GetString("Consolidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos para programar.
        /// </summary>
        internal static string Datos_para_programar {
            get {
                return ResourceManager.GetString("Datos_para_programar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Since.
        /// </summary>
        internal static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery.
        /// </summary>
        internal static string Entrega {
            get {
                return ResourceManager.GetString("Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidation Date.
        /// </summary>
        internal static string Fecha_Consolidacion {
            get {
                return ResourceManager.GetString("Fecha_Consolidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document date.
        /// </summary>
        internal static string Fecha_de_Documento {
            get {
                return ResourceManager.GetString("Fecha_de_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schedule Date.
        /// </summary>
        internal static string Fecha_de_Programación {
            get {
                return ResourceManager.GetString("Fecha_de_Programación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deliver date.
        /// </summary>
        internal static string Fecha_Entrega {
            get {
                return ResourceManager.GetString("Fecha_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date required.
        /// </summary>
        internal static string Fecha_Requerida {
            get {
                return ResourceManager.GetString("Fecha_Requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Until.
        /// </summary>
        internal static string Hasta {
            get {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidation Time.
        /// </summary>
        internal static string Hora_Consolidacion {
            get {
                return ResourceManager.GetString("Hora_Consolidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle Make.
        /// </summary>
        internal static string Marca_Vehiculo {
            get {
                return ResourceManager.GetString("Marca_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tick.
        /// </summary>
        internal static string Marcar {
            get {
                return ResourceManager.GetString("Marcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery Guide Number.
        /// </summary>
        internal static string N_Guia_Entrega {
            get {
                return ResourceManager.GetString("N_Guia_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SN Name.
        /// </summary>
        internal static string Nombre_SN {
            get {
                return ResourceManager.GetString("Nombre_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a legal number.
        /// </summary>
        internal static string Numero_Legal {
            get {
                return ResourceManager.GetString("Numero_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a License No..
        /// </summary>
        internal static string Numero_Licencia {
            get {
                return ResourceManager.GetString("Numero_Licencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference No..
        /// </summary>
        internal static string Numero_Referencia {
            get {
                return ResourceManager.GetString("Numero_Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gross weight.
        /// </summary>
        internal static string Peso_Bruto {
            get {
                return ResourceManager.GetString("Peso_Bruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scheduling dispatches Manual.
        /// </summary>
        internal static string Programación_de_despachos_Manual {
            get {
                return ResourceManager.GetString("Programación_de_despachos_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program.
        /// </summary>
        internal static string Programar {
            get {
                return ResourceManager.GetString("Programar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance.
        /// </summary>
        internal static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Term.
        /// </summary>
        internal static string Termino_Pago {
            get {
                return ResourceManager.GetString("Termino_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data to Consolidate.
        /// </summary>
        internal static string Title_Data_Consolide {
            get {
                return ResourceManager.GetString("Title_Data_Consolide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All documents Selected.
        /// </summary>
        internal static string Total_documentos {
            get {
                return ResourceManager.GetString("Total_documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total weight Selected.
        /// </summary>
        internal static string Total_Peso {
            get {
                return ResourceManager.GetString("Total_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportation.
        /// </summary>
        internal static string Transporte {
            get {
                return ResourceManager.GetString("Transporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ubigeo.
        /// </summary>
        internal static string Ubigeo {
            get {
                return ResourceManager.GetString("Ubigeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle.
        /// </summary>
        internal static string Vehiculo {
            get {
                return ResourceManager.GetString("Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seller.
        /// </summary>
        internal static string Vendedor {
            get {
                return ResourceManager.GetString("Vendedor", resourceCulture);
            }
        }
    }
}
