//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistony.PagosEfectuados.DAL.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Espaniol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Espaniol() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vistony.PagosEfectuados.DAL.Idiomas.Espaniol", typeof(Espaniol).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación de Fecha de despacho.
        /// </summary>
        internal static string Asignación_de_Fecha_de_despacho {
            get {
                return ResourceManager.GetString("Asignación_de_Fecha_de_despacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayudante.
        /// </summary>
        internal static string Ayudante {
            get {
                return ResourceManager.GetString("Ayudante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda.
        /// </summary>
        internal static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda por Rango de Fechas.
        /// </summary>
        internal static string Busqueda_por_Rango_Fecha {
            get {
                return ResourceManager.GetString("Busqueda_por_Rango_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacidad.
        /// </summary>
        internal static string Capacidad {
            get {
                return ResourceManager.GetString("Capacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chofer.
        /// </summary>
        internal static string Chofer {
            get {
                return ResourceManager.GetString("Chofer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo SN.
        /// </summary>
        internal static string Codigo_SN {
            get {
                return ResourceManager.GetString("Codigo_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con Agencia.
        /// </summary>
        internal static string Con_Agencia {
            get {
                return ResourceManager.GetString("Con_Agencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidación de entregas.
        /// </summary>
        internal static string Consolidación_de_entregas {
            get {
                return ResourceManager.GetString("Consolidación_de_entregas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidado.
        /// </summary>
        internal static string Consolidado {
            get {
                return ResourceManager.GetString("Consolidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidar.
        /// </summary>
        internal static string Consolidar {
            get {
                return ResourceManager.GetString("Consolidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos para Programar.
        /// </summary>
        internal static string Datos_para_programar {
            get {
                return ResourceManager.GetString("Datos_para_programar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrega.
        /// </summary>
        internal static string Entrega {
            get {
                return ResourceManager.GetString("Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Consolidacion.
        /// </summary>
        internal static string Fecha_Consolidacion {
            get {
                return ResourceManager.GetString("Fecha_Consolidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Documento.
        /// </summary>
        internal static string Fecha_de_Documento {
            get {
                return ResourceManager.GetString("Fecha_de_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Programación.
        /// </summary>
        internal static string Fecha_de_Programación {
            get {
                return ResourceManager.GetString("Fecha_de_Programación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Entrega.
        /// </summary>
        internal static string Fecha_Entrega {
            get {
                return ResourceManager.GetString("Fecha_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Requerida.
        /// </summary>
        internal static string Fecha_Requerida {
            get {
                return ResourceManager.GetString("Fecha_Requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string Hasta {
            get {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de Consolidacion.
        /// </summary>
        internal static string Hora_Consolidacion {
            get {
                return ResourceManager.GetString("Hora_Consolidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca Vehiculo.
        /// </summary>
        internal static string Marca_Vehiculo {
            get {
                return ResourceManager.GetString("Marca_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar.
        /// </summary>
        internal static string Marcar {
            get {
                return ResourceManager.GetString("Marcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N° Guía Entrega.
        /// </summary>
        internal static string N_Guia_Entrega {
            get {
                return ResourceManager.GetString("N_Guia_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre SN.
        /// </summary>
        internal static string Nombre_SN {
            get {
                return ResourceManager.GetString("Nombre_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a numéro légal.
        /// </summary>
        internal static string Numero_Legal {
            get {
                return ResourceManager.GetString("Numero_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Licencia.
        /// </summary>
        internal static string Numero_Licencia {
            get {
                return ResourceManager.GetString("Numero_Licencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Referencia.
        /// </summary>
        internal static string Numero_Referencia {
            get {
                return ResourceManager.GetString("Numero_Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Bruto.
        /// </summary>
        internal static string Peso_Bruto {
            get {
                return ResourceManager.GetString("Peso_Bruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programación de despachos Manual.
        /// </summary>
        internal static string Programación_de_despachos_Manual {
            get {
                return ResourceManager.GetString("Programación_de_despachos_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programar.
        /// </summary>
        internal static string Programar {
            get {
                return ResourceManager.GetString("Programar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldo.
        /// </summary>
        internal static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Termino de Pago.
        /// </summary>
        internal static string Termino_Pago {
            get {
                return ResourceManager.GetString("Termino_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Consolidado.
        /// </summary>
        internal static string Title_Data_Consolide {
            get {
                return ResourceManager.GetString("Title_Data_Consolide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de documentos.
        /// </summary>
        internal static string Total_documentos {
            get {
                return ResourceManager.GetString("Total_documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Peso.
        /// </summary>
        internal static string Total_Peso {
            get {
                return ResourceManager.GetString("Total_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte.
        /// </summary>
        internal static string Transporte {
            get {
                return ResourceManager.GetString("Transporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubigeo.
        /// </summary>
        internal static string Ubigeo {
            get {
                return ResourceManager.GetString("Ubigeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehiculo.
        /// </summary>
        internal static string Vehiculo {
            get {
                return ResourceManager.GetString("Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendedor.
        /// </summary>
        internal static string Vendedor {
            get {
                return ResourceManager.GetString("Vendedor", resourceCulture);
            }
        }
    }
}
