//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistony.PagosEfectuados.DAL.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Frances {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frances() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vistony.PagosEfectuados.DAL.Idiomas.Frances", typeof(Frances).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Affectation de la date d&apos;expédition.
        /// </summary>
        internal static string Asignación_de_Fecha_de_despacho {
            get {
                return ResourceManager.GetString("Asignación_de_Fecha_de_despacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assistant.
        /// </summary>
        internal static string Ayudante {
            get {
                return ResourceManager.GetString("Ayudante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chercher.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recherche.
        /// </summary>
        internal static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechercher par plage de dates.
        /// </summary>
        internal static string Busqueda_por_Rango_Fecha {
            get {
                return ResourceManager.GetString("Busqueda_por_Rango_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annuler.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aptitude.
        /// </summary>
        internal static string Capacidad {
            get {
                return ResourceManager.GetString("Capacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fermer.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chauffeur.
        /// </summary>
        internal static string Chofer {
            get {
                return ResourceManager.GetString("Chofer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code SN.
        /// </summary>
        internal static string Codigo_SN {
            get {
                return ResourceManager.GetString("Codigo_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avec l&apos;agence.
        /// </summary>
        internal static string Con_Agencia {
            get {
                return ResourceManager.GetString("Con_Agencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidation des livraisons.
        /// </summary>
        internal static string Consolidación_de_entregas {
            get {
                return ResourceManager.GetString("Consolidación_de_entregas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidée.
        /// </summary>
        internal static string Consolidado {
            get {
                return ResourceManager.GetString("Consolidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolider.
        /// </summary>
        internal static string Consolidar {
            get {
                return ResourceManager.GetString("Consolidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos_para_programar.
        /// </summary>
        internal static string Datos_para_programar {
            get {
                return ResourceManager.GetString("Datos_para_programar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depuis.
        /// </summary>
        internal static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a adresse.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Livraison.
        /// </summary>
        internal static string Entrega {
            get {
                return ResourceManager.GetString("Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date de consolidation.
        /// </summary>
        internal static string Fecha_Consolidacion {
            get {
                return ResourceManager.GetString("Fecha_Consolidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date du document.
        /// </summary>
        internal static string Fecha_de_Documento {
            get {
                return ResourceManager.GetString("Fecha_de_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date de planification.
        /// </summary>
        internal static string Fecha_de_Programación {
            get {
                return ResourceManager.GetString("Fecha_de_Programación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date de livraison.
        /// </summary>
        internal static string Fecha_Entrega {
            get {
                return ResourceManager.GetString("Fecha_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date requise.
        /// </summary>
        internal static string Fecha_Requerida {
            get {
                return ResourceManager.GetString("Fecha_Requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jusqu&apos;à.
        /// </summary>
        internal static string Hasta {
            get {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temps de consolidation.
        /// </summary>
        internal static string Hora_Consolidacion {
            get {
                return ResourceManager.GetString("Hora_Consolidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marque du véhicule.
        /// </summary>
        internal static string Marca_Vehiculo {
            get {
                return ResourceManager.GetString("Marca_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marquer.
        /// </summary>
        internal static string Marcar {
            get {
                return ResourceManager.GetString("Marcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a guide de livraison.
        /// </summary>
        internal static string N_Guia_Entrega {
            get {
                return ResourceManager.GetString("N_Guia_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nom du SN.
        /// </summary>
        internal static string Nombre_SN {
            get {
                return ResourceManager.GetString("Nombre_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numéro de livraison.
        /// </summary>
        internal static string Numero_Documento {
            get {
                return ResourceManager.GetString("Numero_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a numéro légal.
        /// </summary>
        internal static string Numero_Legal {
            get {
                return ResourceManager.GetString("Numero_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N ° de licence..
        /// </summary>
        internal static string Numero_Licencia {
            get {
                return ResourceManager.GetString("Numero_Licencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery No..
        /// </summary>
        internal static string Numero_Referencia {
            get {
                return ResourceManager.GetString("Numero_Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poids brut.
        /// </summary>
        internal static string Peso_Bruto {
            get {
                return ResourceManager.GetString("Peso_Bruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manuel de planification des expéditions.
        /// </summary>
        internal static string Programación_de_despachos_Manual {
            get {
                return ResourceManager.GetString("Programación_de_despachos_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programme.
        /// </summary>
        internal static string Programar {
            get {
                return ResourceManager.GetString("Programar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solde.
        /// </summary>
        internal static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terme de paiement.
        /// </summary>
        internal static string Termino_Pago {
            get {
                return ResourceManager.GetString("Termino_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Données à consolider.
        /// </summary>
        internal static string Title_Data_Consolide {
            get {
                return ResourceManager.GetString("Title_Data_Consolide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tous les documents.
        /// </summary>
        internal static string Total_documentos {
            get {
                return ResourceManager.GetString("Total_documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a poids total.
        /// </summary>
        internal static string Total_Peso {
            get {
                return ResourceManager.GetString("Total_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport.
        /// </summary>
        internal static string Transporte {
            get {
                return ResourceManager.GetString("Transporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ubigéo.
        /// </summary>
        internal static string Ubigeo {
            get {
                return ResourceManager.GetString("Ubigeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Véhicule.
        /// </summary>
        internal static string Vehiculo {
            get {
                return ResourceManager.GetString("Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendeur.
        /// </summary>
        internal static string Vendedor {
            get {
                return ResourceManager.GetString("Vendedor", resourceCulture);
            }
        }
    }
}
