//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistony.PagosEfectuados.Win.Constans.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishUnited_States {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishUnited_States() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vistony.PagosEfectuados.Win.Constans.Idioma.EnglishUnited_States", typeof(EnglishUnited_States).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Addon Vistony Distribution.
        /// </summary>
        internal static string AddonName {
            get {
                return ResourceManager.GetString("AddonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load Finished ....
        /// </summary>
        internal static string FinishLoading {
            get {
                return ResourceManager.GetString("FinishLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting Menu Load....
        /// </summary>
        internal static string Message001 {
            get {
                return ResourceManager.GetString("Message001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Loading Menu.
        /// </summary>
        internal static string Message003 {
            get {
                return ResourceManager.GetString("Message003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select date from.
        /// </summary>
        internal static string Message100 {
            get {
                return ResourceManager.GetString("Message100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the date until.
        /// </summary>
        internal static string Message101 {
            get {
                return ResourceManager.GetString("Message101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Worker.
        /// </summary>
        internal static string Message102 {
            get {
                return ResourceManager.GetString("Message102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select State.
        /// </summary>
        internal static string Message103 {
            get {
                return ResourceManager.GetString("Message103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Business Unit.
        /// </summary>
        internal static string Message104 {
            get {
                return ResourceManager.GetString("Message104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Vendor Code.
        /// </summary>
        internal static string Message105 {
            get {
                return ResourceManager.GetString("Message105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date From cannot be less than : {0}.
        /// </summary>
        internal static string Message120 {
            get {
                return ResourceManager.GetString("Message120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next &gt;.
        /// </summary>
        internal static string Message122 {
            get {
                return ResourceManager.GetString("Message122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To finalize.
        /// </summary>
        internal static string Message123 {
            get {
                return ResourceManager.GetString("Message123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispatch is already consolidated.
        /// </summary>
        internal static string Message208 {
            get {
                return ResourceManager.GetString("Message208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document : {0} was consolidated successfully.
        /// </summary>
        internal static string Message209 {
            get {
                return ResourceManager.GetString("Message209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document : {0} is being processed.
        /// </summary>
        internal static string Message210 {
            get {
                return ResourceManager.GetString("Message210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document: {0} assigned to Driver: {1}.
        /// </summary>
        internal static string Message211 {
            get {
                return ResourceManager.GetString("Message211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Step {0} of {1}.
        /// </summary>
        internal static string Message212 {
            get {
                return ResourceManager.GetString("Message212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Did not mark any record.
        /// </summary>
        internal static string Message301 {
            get {
                return ResourceManager.GetString("Message301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in set date range.
        /// </summary>
        internal static string Message302 {
            get {
                return ResourceManager.GetString("Message302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Driver.
        /// </summary>
        internal static string Message303 {
            get {
                return ResourceManager.GetString("Message303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Plate.
        /// </summary>
        internal static string Message304 {
            get {
                return ResourceManager.GetString("Message304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Helper.
        /// </summary>
        internal static string Message305 {
            get {
                return ResourceManager.GetString("Message305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Date.
        /// </summary>
        internal static string Message306 {
            get {
                return ResourceManager.GetString("Message306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to schedule the marked documents?.
        /// </summary>
        internal static string Message307 {
            get {
                return ResourceManager.GetString("Message307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed Driver Assignment.
        /// </summary>
        internal static string Message308 {
            get {
                return ResourceManager.GetString("Message308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to change the dispatch status for the marked documents?.
        /// </summary>
        internal static string Message309 {
            get {
                return ResourceManager.GetString("Message309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a finished process.
        /// </summary>
        internal static string Message310 {
            get {
                return ResourceManager.GetString("Message310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to change the dispatch status to Delivered for the marked documents?.
        /// </summary>
        internal static string Message311 {
            get {
                return ResourceManager.GetString("Message311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a type of Occurrence.
        /// </summary>
        internal static string Message312 {
            get {
                return ResourceManager.GetString("Message312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a type of State.
        /// </summary>
        internal static string Message313 {
            get {
                return ResourceManager.GetString("Message313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select an option to program.
        /// </summary>
        internal static string Message314 {
            get {
                return ResourceManager.GetString("Message314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select date to program.
        /// </summary>
        internal static string Message315 {
            get {
                return ResourceManager.GetString("Message315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a type of consolidation.
        /// </summary>
        internal static string Message316 {
            get {
                return ResourceManager.GetString("Message316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to save {0} to the marked records?.
        /// </summary>
        internal static string Message317 {
            get {
                return ResourceManager.GetString("Message317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document: {0} Could not update {1}.
        /// </summary>
        internal static string Message318 {
            get {
                return ResourceManager.GetString("Message318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to change the dispatch status to Scheduled for the marked documents?.
        /// </summary>
        internal static string Message319 {
            get {
                return ResourceManager.GetString("Message319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding Dispatch Sheet Record.
        /// </summary>
        internal static string Message320 {
            get {
                return ResourceManager.GetString("Message320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to change the dispatch status to Scheduled for the marked documents?.
        /// </summary>
        internal static string Message321 {
            get {
                return ResourceManager.GetString("Message321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to change the dispatch status to Scheduled for the marked documents?.
        /// </summary>
        internal static string Message322 {
            get {
                return ResourceManager.GetString("Message322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Dispatch Sheet was created for the driver &apos;{0}&apos;.
        /// </summary>
        internal static string Message324 {
            get {
                return ResourceManager.GetString("Message324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating Dispatch Tracking.
        /// </summary>
        internal static string Message325 {
            get {
                return ResourceManager.GetString("Message325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated Dispatch Tracking.
        /// </summary>
        internal static string Message326 {
            get {
                return ResourceManager.GetString("Message326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select at least 1 record.
        /// </summary>
        internal static string Message327 {
            get {
                return ResourceManager.GetString("Message327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a State.
        /// </summary>
        internal static string Message328 {
            get {
                return ResourceManager.GetString("Message328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Order is already Scheduled.
        /// </summary>
        internal static string Message329 {
            get {
                return ResourceManager.GetString("Message329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an Occurrence.
        /// </summary>
        internal static string Message330 {
            get {
                return ResourceManager.GetString("Message330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong imei.
        /// </summary>
        internal static string Message331 {
            get {
                return ResourceManager.GetString("Message331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Imei is assigned to another employee \n Do you want to update it ?.
        /// </summary>
        internal static string Message332 {
            get {
                return ResourceManager.GetString("Message332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The IMEI was updated correctly.
        /// </summary>
        internal static string Message333 {
            get {
                return ResourceManager.GetString("Message333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validating Data.
        /// </summary>
        internal static string Message334 {
            get {
                return ResourceManager.GetString("Message334", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tracker Upload Finished.
        /// </summary>
        internal static string MessageFinTracker {
            get {
                return ResourceManager.GetString("MessageFinTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting Tracker Upload.
        /// </summary>
        internal static string MessageInicioTracker {
            get {
                return ResourceManager.GetString("MessageInicioTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data found with the selected criteria.
        /// </summary>
        internal static string NotRowFound {
            get {
                return ResourceManager.GetString("NotRowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAP Business One is not running.
        /// </summary>
        internal static string SAPNotRunning {
            get {
                return ResourceManager.GetString("SAPNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting Charge ....
        /// </summary>
        internal static string StartLoading {
            get {
                return ResourceManager.GetString("StartLoading", resourceCulture);
            }
        }
    }
}
