//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistony.PagosEfectuados.Win.Constans.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Frances {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frances() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vistony.PagosEfectuados.Win.Constans.Idioma.Frances", typeof(Frances).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vistony Complément de distribution.
        /// </summary>
        internal static string AddonName {
            get {
                return ResourceManager.GetString("AddonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chargement terminé ....
        /// </summary>
        internal static string FinishLoading {
            get {
                return ResourceManager.GetString("FinishLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chargement du menu de démarrage....
        /// </summary>
        internal static string Message001 {
            get {
                return ResourceManager.GetString("Message001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur lors du chargement du menu.
        /// </summary>
        internal static string Message003 {
            get {
                return ResourceManager.GetString("Message003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez la date de.
        /// </summary>
        internal static string Message100 {
            get {
                return ResourceManager.GetString("Message100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez la date jusqu&apos;au.
        /// </summary>
        internal static string Message101 {
            get {
                return ResourceManager.GetString("Message101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez le travailleur.
        /// </summary>
        internal static string Message102 {
            get {
                return ResourceManager.GetString("Message102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez l&apos;état.
        /// </summary>
        internal static string Message103 {
            get {
                return ResourceManager.GetString("Message103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez l&apos;unité commerciale.
        /// </summary>
        internal static string Message104 {
            get {
                return ResourceManager.GetString("Message104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez le code fournisseur.
        /// </summary>
        internal static string Message105 {
            get {
                return ResourceManager.GetString("Message105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La date de ne peut pas être inférieure à : {0}.
        /// </summary>
        internal static string Message120 {
            get {
                return ResourceManager.GetString("Message120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suivant &gt;.
        /// </summary>
        internal static string Message122 {
            get {
                return ResourceManager.GetString("Message122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finaliser.
        /// </summary>
        internal static string Message123 {
            get {
                return ResourceManager.GetString("Message123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a L&apos;expédition est déjà consolidée.
        /// </summary>
        internal static string Message208 {
            get {
                return ResourceManager.GetString("Message208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document : {0} a été consolidé avec succès.
        /// </summary>
        internal static string Message209 {
            get {
                return ResourceManager.GetString("Message209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document : {0} est en cours de traitement.
        /// </summary>
        internal static string Message210 {
            get {
                return ResourceManager.GetString("Message210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document : {0} attribué au conducteur : {1}.
        /// </summary>
        internal static string Message211 {
            get {
                return ResourceManager.GetString("Message211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Étape {0} sur {1}.
        /// </summary>
        internal static string Message212 {
            get {
                return ResourceManager.GetString("Message212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N&apos;a marqué aucun enregistrement.
        /// </summary>
        internal static string Message301 {
            get {
                return ResourceManager.GetString("Message301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur dans la plage de dates définie.
        /// </summary>
        internal static string Message302 {
            get {
                return ResourceManager.GetString("Message302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez le pilote.
        /// </summary>
        internal static string Message303 {
            get {
                return ResourceManager.GetString("Message303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionner la plaque.
        /// </summary>
        internal static string Message304 {
            get {
                return ResourceManager.GetString("Message304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez l&apos;assistant.
        /// </summary>
        internal static string Message305 {
            get {
                return ResourceManager.GetString("Message305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionner une date.
        /// </summary>
        internal static string Message306 {
            get {
                return ResourceManager.GetString("Message306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Êtes-vous sûr de planifier les documents marqués ?.
        /// </summary>
        internal static string Message307 {
            get {
                return ResourceManager.GetString("Message307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Affectation de conducteur terminée.
        /// </summary>
        internal static string Message308 {
            get {
                return ResourceManager.GetString("Message308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voulez-vous vraiment modifier le statut d&apos;envoi des documents marqués ?.
        /// </summary>
        internal static string Message309 {
            get {
                return ResourceManager.GetString("Message309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a processus terminé.
        /// </summary>
        internal static string Message310 {
            get {
                return ResourceManager.GetString("Message310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Êtes-vous sûr de changer le statut d&apos;expédition en Livré pour les documents marqués ?.
        /// </summary>
        internal static string Message311 {
            get {
                return ResourceManager.GetString("Message311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez sélectionner un type d&apos;Occurrence.
        /// </summary>
        internal static string Message312 {
            get {
                return ResourceManager.GetString("Message312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez sélectionner un type d&apos;état.
        /// </summary>
        internal static string Message313 {
            get {
                return ResourceManager.GetString("Message313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez sélectionner une option pour programmer.
        /// </summary>
        internal static string Message314 {
            get {
                return ResourceManager.GetString("Message314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez sélectionner la date à programmer.
        /// </summary>
        internal static string Message315 {
            get {
                return ResourceManager.GetString("Message315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez un type de consolidation.
        /// </summary>
        internal static string Message316 {
            get {
                return ResourceManager.GetString("Message316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Êtes-vous sûr d&apos;enregistrer {0} dans les enregistrements marqués ?.
        /// </summary>
        internal static string Message317 {
            get {
                return ResourceManager.GetString("Message317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document : {0} Impossible de mettre à jour {1}.
        /// </summary>
        internal static string Message318 {
            get {
                return ResourceManager.GetString("Message318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Êtes-vous sûr de changer le statut d&apos;envoi en Planifié pour les documents marqués ?.
        /// </summary>
        internal static string Message319 {
            get {
                return ResourceManager.GetString("Message319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajout d&apos;un enregistrement de feuille d&apos;expédition.
        /// </summary>
        internal static string Message320 {
            get {
                return ResourceManager.GetString("Message320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Êtes-vous sûr de changer le statut d&apos;envoi en Planifié pour les documents marqués ?.
        /// </summary>
        internal static string Message321 {
            get {
                return ResourceManager.GetString("Message321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Êtes-vous sûr de changer le statut d&apos;envoi en Planifié pour les documents marqués ?.
        /// </summary>
        internal static string Message322 {
            get {
                return ResourceManager.GetString("Message322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La feuille de répartition a été créée pour le conducteur &apos;{0}&apos;.
        /// </summary>
        internal static string Message324 {
            get {
                return ResourceManager.GetString("Message324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mise à jour du suivi des expéditions.
        /// </summary>
        internal static string Message325 {
            get {
                return ResourceManager.GetString("Message325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mise à jour du suivi des envois.
        /// </summary>
        internal static string Message326 {
            get {
                return ResourceManager.GetString("Message326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez au moins 1 enregistrement.
        /// </summary>
        internal static string Message327 {
            get {
                return ResourceManager.GetString("Message327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionner un état.
        /// </summary>
        internal static string Message328 {
            get {
                return ResourceManager.GetString("Message328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La commande est déjà planifiée.
        /// </summary>
        internal static string Message329 {
            get {
                return ResourceManager.GetString("Message329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sélectionnez une occurrence.
        /// </summary>
        internal static string Message330 {
            get {
                return ResourceManager.GetString("Message330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mauvais imei.
        /// </summary>
        internal static string Message331 {
            get {
                return ResourceManager.GetString("Message331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a L&apos;Imei est attribué à un autre employé \n Voulez-vous le mettre à jour ?.
        /// </summary>
        internal static string Message332 {
            get {
                return ResourceManager.GetString("Message332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a L&apos;IMEI a été mis à jour correctement.
        /// </summary>
        internal static string Message333 {
            get {
                return ResourceManager.GetString("Message333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation des données.
        /// </summary>
        internal static string Message334 {
            get {
                return ResourceManager.GetString("Message334", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chargement du tracker terminé.
        /// </summary>
        internal static string MessageFinTracker {
            get {
                return ResourceManager.GetString("MessageFinTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Démarrage du téléchargement du tracker.
        /// </summary>
        internal static string MessageInicioTracker {
            get {
                return ResourceManager.GetString("MessageInicioTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aucune donnée trouvée avec les critères sélectionnés.
        /// </summary>
        internal static string NotRowFound {
            get {
                return ResourceManager.GetString("NotRowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAP Business One n&apos;est pas en cours d&apos;exécution.
        /// </summary>
        internal static string SAPNotRunning {
            get {
                return ResourceManager.GetString("SAPNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frais de départ ....
        /// </summary>
        internal static string StartLoading {
            get {
                return ResourceManager.GetString("StartLoading", resourceCulture);
            }
        }
    }
}
