//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistony.PagosEfectuados.Win.Constans.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spanish() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vistony.PagosEfectuados.Win.Constans.Idioma.Spanish", typeof(Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vistony Addon de Distribución.
        /// </summary>
        internal static string AddonName {
            get {
                return ResourceManager.GetString("AddonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga Finalizada ....
        /// </summary>
        internal static string FinishLoading {
            get {
                return ResourceManager.GetString("FinishLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando Carga de Menu....
        /// </summary>
        internal static string Message001 {
            get {
                return ResourceManager.GetString("Message001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al Cargar el Menu.
        /// </summary>
        internal static string Message003 {
            get {
                return ResourceManager.GetString("Message003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la fecha desde.
        /// </summary>
        internal static string Message100 {
            get {
                return ResourceManager.GetString("Message100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la fecha hasta.
        /// </summary>
        internal static string Message101 {
            get {
                return ResourceManager.GetString("Message101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Trabajador.
        /// </summary>
        internal static string Message102 {
            get {
                return ResourceManager.GetString("Message102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Estado.
        /// </summary>
        internal static string Message103 {
            get {
                return ResourceManager.GetString("Message103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Unidad de negocio.
        /// </summary>
        internal static string Message104 {
            get {
                return ResourceManager.GetString("Message104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Código de Vendedor.
        /// </summary>
        internal static string Message105 {
            get {
                return ResourceManager.GetString("Message105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Desde no puede ser inferior a : {0}.
        /// </summary>
        internal static string Message120 {
            get {
                return ResourceManager.GetString("Message120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente &gt;.
        /// </summary>
        internal static string Message122 {
            get {
                return ResourceManager.GetString("Message122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string Message123 {
            get {
                return ResourceManager.GetString("Message123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Despacho ya se encuentra consolidado.
        /// </summary>
        internal static string Message208 {
            get {
                return ResourceManager.GetString("Message208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento : {0}  fue consolidado satisfactoriamente.
        /// </summary>
        internal static string Message209 {
            get {
                return ResourceManager.GetString("Message209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento : {0} se esta procesando.
        /// </summary>
        internal static string Message210 {
            get {
                return ResourceManager.GetString("Message210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento :  {0} asignado al  Chofer:  {1}.
        /// </summary>
        internal static string Message211 {
            get {
                return ResourceManager.GetString("Message211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso  {0} de {1}.
        /// </summary>
        internal static string Message212 {
            get {
                return ResourceManager.GetString("Message212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Marcó ningún registro.
        /// </summary>
        internal static string Message301 {
            get {
                return ResourceManager.GetString("Message301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en rango de fechas establecido.
        /// </summary>
        internal static string Message302 {
            get {
                return ResourceManager.GetString("Message302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Chofer.
        /// </summary>
        internal static string Message303 {
            get {
                return ResourceManager.GetString("Message303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Placa.
        /// </summary>
        internal static string Message304 {
            get {
                return ResourceManager.GetString("Message304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Ayudante.
        /// </summary>
        internal static string Message305 {
            get {
                return ResourceManager.GetString("Message305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Fecha.
        /// </summary>
        internal static string Message306 {
            get {
                return ResourceManager.GetString("Message306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro de hacer la programación de los documentos marcados?.
        /// </summary>
        internal static string Message307 {
            get {
                return ResourceManager.GetString("Message307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación de Chofer Culminada.
        /// </summary>
        internal static string Message308 {
            get {
                return ResourceManager.GetString("Message308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro de cambiar el estado de despacho para los documentos marcados?.
        /// </summary>
        internal static string Message309 {
            get {
                return ResourceManager.GetString("Message309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso Culminado.
        /// </summary>
        internal static string Message310 {
            get {
                return ResourceManager.GetString("Message310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro de cambiar el estado de despacho a Entregado para los documentos marcados?.
        /// </summary>
        internal static string Message311 {
            get {
                return ResourceManager.GetString("Message311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un tipo de Ocurrencia.
        /// </summary>
        internal static string Message312 {
            get {
                return ResourceManager.GetString("Message312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un tipo de Estado.
        /// </summary>
        internal static string Message313 {
            get {
                return ResourceManager.GetString("Message313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una opción a programar.
        /// </summary>
        internal static string Message314 {
            get {
                return ResourceManager.GetString("Message314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar data a programar.
        /// </summary>
        internal static string Message315 {
            get {
                return ResourceManager.GetString("Message315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un tipo de consolidado.
        /// </summary>
        internal static string Message316 {
            get {
                return ResourceManager.GetString("Message316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está Seguro de grabar al {0} a los registros marcados?.
        /// </summary>
        internal static string Message317 {
            get {
                return ResourceManager.GetString("Message317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento: {0}   No se pudo actualizar {1}.
        /// </summary>
        internal static string Message318 {
            get {
                return ResourceManager.GetString("Message318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro de cambiar el estado de despacho a Programado para los documentos marcados?.
        /// </summary>
        internal static string Message319 {
            get {
                return ResourceManager.GetString("Message319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregando Registro de Hoja de despacho.
        /// </summary>
        internal static string Message320 {
            get {
                return ResourceManager.GetString("Message320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro de cambiar el estado de despacho a Programado para los documentos marcados?.
        /// </summary>
        internal static string Message321 {
            get {
                return ResourceManager.GetString("Message321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de cambiar el estado de despacho a Programado para los documentos marcados?.
        /// </summary>
        internal static string Message322 {
            get {
                return ResourceManager.GetString("Message322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se creo la Hoja de despacho para el chofer &apos;{0}&apos;.
        /// </summary>
        internal static string Message324 {
            get {
                return ResourceManager.GetString("Message324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acualizando Seguimiento de Despacho.
        /// </summary>
        internal static string Message325 {
            get {
                return ResourceManager.GetString("Message325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimiento de Despacho Actualizados.
        /// </summary>
        internal static string Message326 {
            get {
                return ResourceManager.GetString("Message326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona minimo 1 registro.
        /// </summary>
        internal static string Message327 {
            get {
                return ResourceManager.GetString("Message327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un Estado.
        /// </summary>
        internal static string Message328 {
            get {
                return ResourceManager.GetString("Message328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Pedido ya se encuentra Programado.
        /// </summary>
        internal static string Message329 {
            get {
                return ResourceManager.GetString("Message329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una Ocurrencia.
        /// </summary>
        internal static string Message330 {
            get {
                return ResourceManager.GetString("Message330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imei Incorrecto.
        /// </summary>
        internal static string Message331 {
            get {
                return ResourceManager.GetString("Message331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Imei Esta Asignado a otro empleado \n ¿ Desea Actualizarlo ?.
        /// </summary>
        internal static string Message332 {
            get {
                return ResourceManager.GetString("Message332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se Actualizo Correctamente el IMEI.
        /// </summary>
        internal static string Message333 {
            get {
                return ResourceManager.GetString("Message333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando Datos.
        /// </summary>
        internal static string Message334 {
            get {
                return ResourceManager.GetString("Message334", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga de Tracker Finalizado.
        /// </summary>
        internal static string MessageFinTracker {
            get {
                return ResourceManager.GetString("MessageFinTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando Carga de Tracker.
        /// </summary>
        internal static string MessageInicioTracker {
            get {
                return ResourceManager.GetString("MessageInicioTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron datos con los criterios seleccionados.
        /// </summary>
        internal static string NotRowFound {
            get {
                return ResourceManager.GetString("NotRowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAP Business One, no se encuentra ejecutandose.
        /// </summary>
        internal static string SAPNotRunning {
            get {
                return ResourceManager.GetString("SAPNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando Carga ....
        /// </summary>
        internal static string StartLoading {
            get {
                return ResourceManager.GetString("StartLoading", resourceCulture);
            }
        }
    }
}
